name: "MCP Client OAuth Proxy (DEV)"
slug: "mcp-client-oauth-proxy-dev"
image: "ghcr.io/connormxy/mcp-client-oauth-proxy-dev"
version: "0.1.0-dev.11"
stage: experimental
url: "https://github.com/connormxy/homeassistant-app-mcp-oauth-proxy#dev"
description: "OAuth 2.1 proxy allowing MCP clients to access OAuth-protected MCP servers. (DEV)"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ports:
  8090/tcp: 8098
options:
  log_level: "debug"
  oauth_client_id: "your-client-id"
  oauth_client_secret: "your-client-secret"
  oauth_authorize_url: "https://ifttt.com"
  scopes_supported: "mcp"
  mcp_server_url: "https://ifttt.com"
  encryption_key: "base64-encoded-32-byte-aes-key"
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  oauth_client_id: str
  oauth_client_secret: str
  oauth_authorize_url: str
  scopes_supported: str
  mcp_server_url: str
  encryption_key: str